language: python
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.cache/pip"
python:
- "2.7"
addons:
  apt:
    sources:
    - pov-wkhtmltopdf
    packages:
    - expect-dev
    - python-lxml
    - python-simplejson
    - python-serial
    - python-yaml
    - sshpass
    - wkhtmltopdf
  postgresql: "9.3"
env:
  global:
  - VERSION="8.0" LINT_CHECK="0" TRANSIFEX="0" GRAPHJS="0" MOBJS="0"
  matrix:
  - LINT_CHECK="1" TESTS="0"

# Check all the observation types separately
  - ODOO_REPO="valdecdev/odoo" TESTS="1"
    EXCLUDE="base,web,nh_odoo_fixes,nh_activity,nh_clinical,nh_gcs,nh_graphs,nh_neurovascular,nh_observations,nh_pbp,nh_stools,nh_urinary_analysis,nh_vips,nh_eobs,nh_eobs_api,nh_eobs_backup,nh_eobs_default,nh_eobs_kiosk,nh_eobs_theme,nh_eobs_mobile,xml_test_output"
    INCLUDE="nh_ews"
    VERSION="openeobs-8-12"

  - ODOO_REPO="valdecdev/odoo" TESTS="1"
    EXCLUDE="base,web,nh_odoo_fixes,nh_activity,nh_clinical,nh_ews,nh_graphs,nh_neurovascular,nh_observations,nh_pbp,nh_stools,nh_urinary_analysis,nh_vips,nh_eobs,nh_eobs_api,nh_eobs_backup,nh_eobs_default,nh_eobs_kiosk,nh_eobs_theme,nh_eobs_mobile,xml_test_output"
    INCLUDE="nh_gcs"
    VERSION="openeobs-8-12"

  - ODOO_REPO="valdecdev/odoo" TESTS="1"
    EXCLUDE="base,web,nh_odoo_fixes,nh_activity,nh_ews,nh_gcs,nh_neurovascular,nh_observations,nh_pbp,nh_stools,nh_urinary_analysis,nh_vips,nh_eobs,nh_eobs_api,nh_eobs_backup,nh_eobs_default,nh_eobs_kiosk,nh_eobs_theme,nh_eobs_mobile,xml_test_output"
    INCLUDE="nh_clinical,nh_graphs"
    VERSION="openeobs-8-12"

  - ODOO_REPO="valdecdev/odoo" TESTS="1"
    EXCLUDE="base,web,nh_odoo_fixes,nh_activity,nh_clinical,nh_ews,nh_gcs,nh_graphs,nh_observations,nh_pbp,nh_stools,nh_urinary_analysis,nh_vips,nh_eobs,nh_eobs_api,nh_eobs_backup,nh_eobs_default,nh_eobs_kiosk,nh_eobs_theme,nh_eobs_mobile,xml_test_output"
    INCLUDE="nh_neurovascular"
    VERSION="openeobs-8-12"

  - ODOO_REPO="valdecdev/odoo" TESTS="1"
    EXCLUDE="base,web,nh_odoo_fixes,nh_activity,nh_clinical,nh_ews,nh_gcs,nh_graphs,nh_neurovascular,nh_pbp,nh_stools,nh_urinary_analysis,nh_vips,nh_eobs,nh_eobs_api,nh_eobs_backup,nh_eobs_default,nh_eobs_kiosk,nh_eobs_theme,nh_eobs_mobile,xml_test_output"
    INCLUDE="nh_observations"
    VERSION="openeobs-8-12"

  - ODOO_REPO="valdecdev/odoo" TESTS="1"
    EXCLUDE="base,web,nh_odoo_fixes,nh_activity,nh_clinical,nh_ews,nh_gcs,nh_graphs,nh_neurovascular,nh_observations,nh_stools,nh_urinary_analysis,nh_vips,nh_eobs,nh_eobs_api,nh_eobs_backup,nh_eobs_default,nh_eobs_kiosk,nh_eobs_theme,nh_eobs_mobile,xml_test_output"
    INCLUDE="nh_pbp"
    VERSION="openeobs-8-12"

  - ODOO_REPO="valdecdev/odoo" TESTS="1"
    EXCLUDE="base,web,nh_odoo_fixes,nh_activity,nh_clinical,nh_ews,nh_gcs,nh_graphs,nh_neurovascular,nh_observations,nh_pbp,nh_urinary_analysis,nh_vips,nh_eobs,nh_eobs_api,nh_eobs_backup,nh_eobs_default,nh_eobs_kiosk,nh_eobs_theme,nh_eobs_mobile,xml_test_output"
    INCLUDE="nh_stools"
    VERSION="openeobs-8-12"

  - ODOO_REPO="valdecdev/odoo" TESTS="1"
    EXCLUDE="base,web,nh_odoo_fixes,nh_activity,nh_clinical,nh_ews,nh_gcs,nh_graphs,nh_neurovascular,nh_observations,nh_pbp,nh_stools,nh_vips,nh_eobs,nh_eobs_api,nh_eobs_backup,nh_eobs_default,nh_eobs_kiosk,nh_eobs_theme,nh_eobs_mobile,xml_test_output"
    INCLUDE="nh_urinary_analysis"
    VERSION="openeobs-8-12"

  - ODOO_REPO="valdecdev/odoo" TESTS="1"
    EXCLUDE="base,web,nh_odoo_fixes,nh_activity,nh_clinical,nh_ews,nh_gcs,nh_graphs,nh_neurovascular,nh_observations,nh_pbp,nh_stools,nh_urinary_analysis,nh_eobs,nh_eobs_api,nh_eobs_backup,nh_eobs_default,nh_eobs_kiosk,nh_eobs_theme,nh_eobs_mobile,xml_test_output"
    INCLUDE="nh_vips"
    VERSION="openeobs-8-12"

# Test nh_graph GraphLib JS
  - GRAPHJS="1"

# Test nh_eob_mobile NHMobile JS
  - MOBJS="1"

# Check all the observation types together
  - ODOO_REPO="valdecdev/odoo" TESTS="1"
    EXCLUDE="base,web,nh_odoo_fixes,nh_activity,nh_clinical,nh_eobs,nh_eobs_api,nh_eobs_backup,nh_eobs_default,nh_eobs_kiosk,nh_eobs_theme,nh_eobs_mobile,xml_test_output"
    INCLUDE="nh_ews,nh_gcs,nh_graphs,nh_neurovascular,nh_observations,nh_pbp,nh_stools,nh_urinary_analysis,nh_vips"
    VERSION="openeobs-8-12"

# Check open-eObs modules
  - ODOO_REPO="valdecdev/odoo" TESTS="1"
    EXCLUDE="base,web,nh_odoo_fixes,nh_activity,nh_clinical,nh_ews,nh_gcs,nh_neurovascular,nh_observations,nh_pbp,nh_stools,nh_urinary_analysis,nh_vips,nh_graphs,nh_eobs_mobile,xml_test_output"
    INCLUDE="nh_eobs,nh_eobs_api,nh_eobs_backup,nh_eobs_default,nh_eobs_kiosk,nh_eobs_theme"
    VERSION="openeobs-8-12"

  - ODOO_REPO="valdecdev/odoo" TESTS="1"
    EXCLUDE="base,web,nh_odoo_fixes,nh_activity,nh_clinical,nh_ews,nh_gcs,nh_neurovascular,nh_observations,nh_pbp,nh_stools,nh_urinary_analysis,nh_vips,nh_graphs,nh_eobs,nh_eobs_api,nh_eobs_backup,nh_eobs_default,nh_eobs_kiosk,nh_eobs_theme,web,xml_test_output"
    INCLUDE="nh_eobs_mobile"
    VERSION="openeobs-8-12"

  - ODOO_REPO="valdecdev/odoo" TESTS="1"
    EXCLUDE="base,web,nh_odoo_fixes,nh_activity,nh_clinical,xml_test_output"
    INCLUDE="nh_ews,nh_gcs,nh_graphs,nh_neurovascular,nh_observations,nh_pbp,nh_stools,nh_urinary_analysis,nh_vips,nh_eobs,nh_eobs_api,nh_eobs_backup,nh_eobs_default,nh_eobs_kiosk,nh_eobs_theme,nh_eobs_mobile"
    VERSION="openeobs-8-12"

virtualenv:
  system_site_packages: true
before_install:
- export TZ=UTC
- git clone https://github.com/NeovaHealth/nhclinical.git NeovaHealth/nhclinical
- cd NeovaHealth/nhclinical
- find_branch() { git show-ref refs/remotes/origin/${TRAVIS_BRANCH} && git checkout ${TRAVIS_BRANCH}; return 0; }; find_branch
- mkdir -p ${HOME}/dependencies
- for DIRECTORY in *; do mv ${DIRECTORY} ${HOME}/dependencies/${DIRECTORY}; done
- cd ../..
- git clone --depth=50 https://github.com/Gimpneek/odoo_xml_test_output.git odoo_xml_test_output
- cd odoo_xml_test_output
- pip install -r requirements.txt
- pip install astroid==1.3.8
- mv xml_test_output ${HOME}/dependencies/xml_test_output
- cd ${TRAVIS_BUILD_DIR}
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
- export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
- if [ "$GRAPHJS" == "0" ] && [ "$MOBJS" == "0" ] ; then travis_install_nightly ; fi
- if [ "$GRAPHJS" == "1" ] ; then cd nh_graphs/dev/coffee; npm install; fi
- if [ "$MOBJS" == "1" ] ; then cd nh_eobs_mobile/static/dev/coffee; npm cache clean; npm install; fi
script:
- if [ "$GRAPHJS" == "0" ] && [ "$MOBJS" == "0" ] ; then travis_run_tests ; fi
- if [ "$GRAPHJS" == "1" ] ; then gulp karma ; fi
- if [ "$MOBJS" == "1" ] ; then gulp travis ; fi
after_script:
- coverage xml -o ${HOME}/build/NeovaHealth/openeobs/coverage.xml
- cd ${HOME}/build/NeovaHealth/openeobs
- echo "<?xml version=\"1.0\" encoding=\"utf-8\"?><testsuites>" > test_report.xml
- for rep in ${HOME}/tests/*.xml; do cat "$rep" | grep -v "<?xml " >> test_report.xml;
  done
- echo "</testsuites>" >> test_report.xml
